name: Deploy dev

on:
  pull_request:
    types: [closed]
    branches: [dev]

concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy-reusable.yml
    with:
      environment: dev
      cluster: cluster-dev
      service: mi-app-dev
      image-tag: dev-latest
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEV_DEPLOY_ROLE_ARN }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}