name: Deploy prod

on:
  workflow_run:
    workflows:
      - CI
    types: 
      - completed
    branches:
      - main

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/_deploy-reusable.yml

    with:
      environment: production
      cluster: cluster-prod
      service: mi-app-prod
      image-tag: main-latest

    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.PROD_DEPLOY_ROLE_ARN }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}